##titre NOTE : you need to use the "all bluetooth" version to use it as intended
//================
How to use this beacon? 

How to transmit data to the beacon : -install a serial blutooth android app -make sure that "Newline" is "None"

Every command is composed of 3 mains part : -Password("pswd" in code) -the part you want to change("n" in code) -String or float

2 possibilities: -"pswd,n,x,y" (for the coord part) -"pswd,nString"(for all the other parts)

n list : -0 coordinates -1 name of the beacon -2 description -3 local news -4 owner

The password ensure that the beacon's owner stays authentified. You cannot change the String "owner" without the good password. All other field are still open with any other number, in the serial communication you can type any number for pswd.


//============================================================================
= Liquid Crystal Library for Arduino =

This library allows an Arduino board to control LiquidCrystal displays (LCDs) based on the Hitachi HD44780 (or a compatible) chipset, which is found on most text-based LCDs.

For more information about this library please visit us at
http://www.arduino.cc/en/Reference/LiquidCrystal

== License ==

Copyright (C) 2006-2008 Hans-Christoph Steiner. All rights reserved.
Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
